# MSLab LabConfig for Azure Local (single-node)
# This file is auto-generated by Deploy-AzureLocal.ps1 from config.ps1 values.
# You can also edit it directly and run MSLab's Deploy.ps1 manually.

# Load config if available
$configPath = Join-Path $PSScriptRoot "config.ps1"
if (Test-Path $configPath) { . $configPath }

# Defaults
if (-not $NodeCount)    { $NodeCount = 1 }
if (-not $NodeMemoryGB) { $NodeMemoryGB = 20 }
if (-not $NodeHDDCount) { $NodeHDDCount = 4 }
if (-not $NodeHDDSizeGB){ $NodeHDDSizeGB = 1024 }
if (-not $ClusterName)  { $ClusterName = "ALab01" }

$LabConfig = @{
    AllowedVLANs           = "1-10,711-719"
    DomainAdminName        = 'LabAdmin'
    AdminPassword          = 'LS1setup!'
    DCEdition              = '4'
    Internet               = $true
    AdditionalNetworksConfig = @()
    VMs                    = @()
}

# Azure Local nodes
1..$NodeCount | ForEach-Object {
    $LabConfig.VMs += @{
        VMName             = "${ClusterName}Node$_"
        Configuration      = 'S2D'
        ParentVHD          = 'AzSHCI24H2_G2.vhdx'
        HDDNumber          = $NodeHDDCount
        HDDSize            = "${NodeHDDSizeGB}GB" -as [UInt64] * 1GB
        MemoryStartupBytes = $NodeMemoryGB * 1GB
        VMProcessorCount   = "MAX"
        vTPM               = $true
        Unattend           = "NoDjoin"
        NestedVirt         = $true
    }
}

# Management VM (Windows Server 2025 with GUI)
$LabConfig.VMs += @{
    VMName      = 'Management'
    ParentVHD   = 'Win2025_G2.vhdx'
    MGMTNICs    = 1
    AddToolsVHD = $true
}
